# ==========================================================
# üé® StyLua Configuration
# Format Lua code consistently and beautifully
# https://github.com/JohnnyMorganz/StyLua
# ==========================================================

# ----------------------------------------------------------
# üß© Core Settings
# ----------------------------------------------------------
syntax = "Lua54"
column_width = 119
line_endings = "Unix"

# ----------------------------------------------------------
# üîß Indentation Rules
# ----------------------------------------------------------
indent_type = "Tabs"
indent_width = 2

# ----------------------------------------------------------
# ‚úçÔ∏è Quotation and Statement Style
# ----------------------------------------------------------
quote_style = "AutoPreferDouble"
collapse_simple_statement = "Always"
call_parentheses = "Always"

# ----------------------------------------------------------
# üì¶ Require Sorting
# ----------------------------------------------------------
[sort_requires]
enabled = true
