
#  ~/.config/nvim/.stylua.toml StyLua Configuration
# Reference:
# - https://github.com/JohnnyMorganz/StyLua
# - https://github.com/gen740/SmoothCursor.nvim/blob/main/.stylua.toml

# Formatting behavior
column_width       = 100
line_endings       = "Unix"
indent_type        = "Spaces"
indent_width       = 2
quote_style        = "AutoPreferDouble"  # Options: AutoPreferDouble | AutoPreferSingle
call_parentheses   = "Always"            # Options: Always | NoSingleTable
no_call_parentheses = false              # Always use parentheses for function calls
syntax             = "Lua54"             # Use Lua 5.4 parser

